[package]
name = "lay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
pest = "2.7.8"
pest_ascii_tree = "0.1.0"
pest_derive = "2.7.8"
rustyline = "13.0.0"
